name = "AdventOfCode2023"
uuid = "f2ee7879-578e-46fe-aaf2-38393bf3ac16"
authors = ["Joao Areias <joaoareiasmoraes@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
